---
- name: Apply Common Setup
  hosts: all
  become: true
  roles:
    - common

- name: Deploy Node Exporters
  hosts: node_exporter_nodes
  become: true
  roles:
    - node_exporter

- name: Deploy Prometheus Server
  hosts: prometheus_server
  become: true
  roles:
    - prometheus

- name: Deploy Grafana
  hosts: grafana_server
  become: true
  roles:
    - grafana

- name: Deploy Target Node Exporters
  hosts: node_exporter_nodes
  become: true
  roles:
    - role: node_exporter
    - role: postgres_exporter
      when: "'postgres' in (exporters | default([]))"
    - role: redis_exporter
      when: "'redis' in (exporters | default([]))"
    - role: rabbitmq_exporter
      when: "'rabbitmq' in (exporters | default([]))"
