---
- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.54.1/prometheus-2.54.1.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0644'

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Copy Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-2.54.1.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: true
  loop:
    - prometheus
    - promtool

- name: Deploy Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart prometheus

- name: Create Prometheus systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
    content: |
      [Unit]
      Description=Prometheus Server
      After=network.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd
    - Restart prometheus

- name: Ensure Prometheus is running and enabled
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
